### ISSUE TITLE
Decide on labeling strategy

### ISSUE THREAD

**Issue by dorukbu** [swe574-Fall2024-Group1/csims#2]

**Comment by qouv** [comment]
I think we should also add backend and frontend labels. What do you guys think @DorukBu @aaldaber @erkingonultas?

**Comment by qouv** [comment]
What should be the label of this issue btw?

**Comment by erkingonultas** [comment]
I agree. Frontend, Backend, Mobile tags would make it easier to work with. I couldn't decide on a label for this issue too, so maybe a simple Decision tag would be ok for this kind of issues.

**Comment by dorukbu** [comment]
Frontend, Backend, Mobile, and Decision labels are created
